  name: exercise workflow
  on: [push, workflow_dispatch]
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name : install dependencies
          run: npm install
        - name: lint
          run: npm run lint
        - name: test
          run: npm run test
    build:
      runs-on: ubuntu-latest
      steps:
        - name:
